# Generated by Django 2.1 on 2018-08-10 17:29

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20180810_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(upload_to=gallery.models.user_directory_path),
        ),
    ]
