# Generated by Django 2.1 on 2018-08-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_feed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
