# Generated by Django 2.1 on 2018-08-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20180813_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
